#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

// ADCMUX REFERANCE SELECTION BIT
#define ADMUX_REFS1     7
#define ADMUX_REFS0     6
#define ADMUX_ADLAR     5

// ADC CONTROL AND STATUS REGISTER
#define ADCSRA_ADEN     7 //ADC ENABLE
#define ADCSRA_ADSC     6 //ADC START CONVERSION
#define ADCSRA_ADTE     5 //ADC AUTO TRIGGER INTERRUPT
#define ADCSRA_ADIF     4 //ADC INTERRUPT FLAG
#define ADCSRA_ADIE     3 //ADC INTERRUPT ENABLE
#define ADCSRA_ADPS2    2 //CLOCK PRESCALAR
#define ADCSRA_ADPS1    1 //CLOCK PRESCALAR
#define ADCSRA_ADPS0    0 //CLOCK PRESCALAR



#endif
